apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: in-progress-repo-cache
spec:
  clusterName: infinispan
  name: in-progress-repo-cache
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "2"
      statistics: "true"
      encoding:
        mediaType: "text/plain"
